sudo: true

services:
  - docker

env:
    matrix:
      - OS=ubuntu DIST=16 PACK=deb

language: c++

compiler:
  - g++

addons:
  apt:
    packages:
      - cmake
      - bison
      - flex

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest .
