sudo: true

services:
  - docker

branches:
  only:
    - master
    - dev

env:
  matrix:
    - OS=ubuntu DIST=16 PACK=deb

language: c++

compiler:
  - g++
  - clang

addons:
  apt:
    packages:
      - cmake
      - bison
      - flex

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest .
