language: c++
dist: trusty

compiler:
    - gcc

addons:
    apt:
        sources:
            - kalakris-cmake
        packages:
            - cmake
            - bison
            - flex

script:
  - mkdir build && cd build && cmake .. && cmake --build .
