sudo: true

services:
  - docker

env:
    matrix:
      - OS=ubuntu DIST=xenial PACK=deb

language: c++

compiler:
  - g++

addons:
  apt:
    packages:
      - cmake
      - bison
      - flex

script:
  - mkdir build && cd build && cmake .. && cmake --build .
