sudo: true

services:
  - docker

branches:
  - master
  - dev

env:
  matrix:
    - OS=ubuntu DIST=16 PACK=deb

language: c++

compiler:
  - g++
  - clang

addons:
  apt:
    packages:
      - cmake
      - bison
      - flex

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - cmake --build .
  - ctest --output-on-failure .

notifications:
  email: false
